name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: |
          cd apps/finesite
          npm run build

      - name: Run tests (if they exist)
        run: |
          cd apps/finesite
          npm run test --if-present
        continue-on-error: true

      - name: Check build artifacts
        run: |
          cd apps/finesite
          ls -la dist/